version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/fdk-python
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
            pip install -r requirements.txt
      - run: docker version
      - run: docker pull fnproject/fnserver
      # installing Fn CLI and starting the Fn server
      - run:
          command: |
            curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            tox -epep8
      - run:
          command: |
            . venv/bin/activate
            tox -epy3.7
