version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/fdk-python
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            sudo apt-get install curl
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install build-essential nodejs -qy
            npm -v
            sudo npm install -g snyk
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
            pip install -r requirements.txt
      - run: docker version
      - run: docker pull fnproject/fnserver
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            tox -epep8
      - run:
          command: |
            . venv/bin/activate
            tox -epy3.7
      # TODO: add SNYK_TOKEN to CI config,
      # enable two checks after that.
      # - run:
      #     command: |
      #       ./build-images.sh 3.7.1
      #       ./test-images.sh 3.7.1
      # - run:
      #     command: |
      #       ./build-images.sh 3.6
      #       ./test-images.sh 3.6
