schema_version: 20180708
name: python3-fn-gpi
version: 0.0.6
runtime: python3.7
entrypoint: python3 func.py
format: json
triggers:
- name: python3-fn-gpi-trigger
  type: http
  source: /python3-fn-gpi-trigger
