FROM docker-remote.artifactory.oci.oraclecorp.com/oraclelinux:8-slim

RUN microdnf install -y python36 &&\
    microdnf clean all

RUN pip3 install --upgrade pip && pip3 cache purge

ARG RPM_VERSION=latest
ENV RPM_VERSION=${RPM_VERSION:-v1.0.0}


RUN microdnf -y install gzip \
    zip \
    tar \
    rpm \
    rpm-build \
    binutils \
    freetype fontconfig

RUN microdnf clean all

RUN mkdir -p /root/rpmbuild/SOURCES

RUN mkdir /fdk-python
WORKDIR /fdk-python

COPY ./requirements.txt /fdk-python 
COPY ./internal/build-scripts/rpm/fdk-python36.spec  /fdk-python
COPY ./internal/build-scripts/rpm/copy_rpm.sh /fdk-python 

RUN mkdir ./fdk_dependencies
RUN pip3 download -d ./fdk_dependencies --no-cache --no-cache-dir -r requirements.txt
COPY ./dist/*whl ./python/

COPY ./LICENSE ./python/
COPY ./THIRD_PARTY_LICENSES.txt ./python/

RUN tar cvf fdk-$RPM_VERSION.tar.gz ./python

RUN cp  fdk-$RPM_VERSION.tar.gz ~/rpmbuild/SOURCES
RUN cp -r ./fdk_dependencies/* ~/rpmbuild/SOURCES 

RUN rpmbuild --define "_rpm_version ${RPM_VERSION}"  -ba fdk-python36.spec 